language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"


# test script
before_script:
  - cmake .
script:
  - ctest -VV --output-on-failure .

addons:
 apt:
   packages:
   - cmake


# Notify the mailing list
notifications:
  email:
    on_success: change
    on_failure: always
